/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizationRouteRouteImport } from './routes/visualization/route'
import { Route as GamesRouteRouteImport } from './routes/games/route'
import { Route as EducationRouteRouteImport } from './routes/education/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualizationIndexRouteImport } from './routes/visualization/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as EducationIndexRouteImport } from './routes/education/index'
import { Route as VisualizationOsmdParserRouteImport } from './routes/visualization/osmd-parser'
import { Route as VisualizationMetronomeRouteImport } from './routes/visualization/metronome'
import { Route as GamesDrumMachineRouteImport } from './routes/games/drum-machine'
import { Route as GamesAndIWillAlwaysLoveYouRouteImport } from './routes/games/And I Will Always Love You'
import { Route as EducationGenresIndexRouteImport } from './routes/education/genres/index'
import { Route as VisualizationRhythmsRhythmVisualRouteImport } from './routes/visualization/rhythms/rhythm-visual'
import { Route as VisualizationRhythmsRhythmIndexRouteImport } from './routes/visualization/rhythms/RhythmIndex'
import { Route as VisualizationRhythmsRhythmIdRouteImport } from './routes/visualization/rhythms/$rhythmId'
import { Route as VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRouteImport } from './routes/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
import { Route as EducationTheoryRhythmEducationRouteImport } from './routes/education/theory/rhythm-education'
import { Route as EducationTheoryIntroductionRouteImport } from './routes/education/theory/Introduction'
import { Route as EducationGenresRockRouteImport } from './routes/education/genres/Rock'
import { Route as EducationGenresPunkRouteImport } from './routes/education/genres/Punk'
import { Route as EducationGenresProgRouteImport } from './routes/education/genres/Prog'
import { Route as EducationGenresPopRouteImport } from './routes/education/genres/Pop'
import { Route as EducationGenresMetalRouteImport } from './routes/education/genres/Metal'
import { Route as EducationGenresJazzRouteImport } from './routes/education/genres/Jazz'
import { Route as EducationGenresHipHopRouteImport } from './routes/education/genres/HipHop'
import { Route as EducationGenresGlossaryRouteImport } from './routes/education/genres/Glossary'
import { Route as EducationGenresEDMRouteImport } from './routes/education/genres/EDM'
import { Route as EducationGenresAfroCubanRouteImport } from './routes/education/genres/AfroCuban'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const VisualizationRouteRoute = VisualizationRouteRouteImport.update({
  id: '/visualization',
  path: '/visualization',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRouteRoute = GamesRouteRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRouteRoute = EducationRouteRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationIndexRoute = VisualizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisualizationRouteRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRouteRoute,
} as any)
const EducationIndexRoute = EducationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducationRouteRoute,
} as any)
const VisualizationOsmdParserRoute = VisualizationOsmdParserRouteImport.update({
  id: '/osmd-parser',
  path: '/osmd-parser',
  getParentRoute: () => VisualizationRouteRoute,
} as any)
const VisualizationMetronomeRoute = VisualizationMetronomeRouteImport.update({
  id: '/metronome',
  path: '/metronome',
  getParentRoute: () => VisualizationRouteRoute,
} as any)
const GamesDrumMachineRoute = GamesDrumMachineRouteImport.update({
  id: '/drum-machine',
  path: '/drum-machine',
  getParentRoute: () => GamesRouteRoute,
} as any)
const GamesAndIWillAlwaysLoveYouRoute =
  GamesAndIWillAlwaysLoveYouRouteImport.update({
    id: '/And I Will Always Love You',
    path: '/And I Will Always Love You',
    getParentRoute: () => GamesRouteRoute,
  } as any)
const EducationGenresIndexRoute = EducationGenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => EducationRouteRoute,
} as any)
const VisualizationRhythmsRhythmVisualRoute =
  VisualizationRhythmsRhythmVisualRouteImport.update({
    id: '/rhythms/rhythm-visual',
    path: '/rhythms/rhythm-visual',
    getParentRoute: () => VisualizationRouteRoute,
  } as any)
const VisualizationRhythmsRhythmIndexRoute =
  VisualizationRhythmsRhythmIndexRouteImport.update({
    id: '/rhythms/RhythmIndex',
    path: '/rhythms/RhythmIndex',
    getParentRoute: () => VisualizationRouteRoute,
  } as any)
const VisualizationRhythmsRhythmIdRoute =
  VisualizationRhythmsRhythmIdRouteImport.update({
    id: '/rhythms/$rhythmId',
    path: '/rhythms/$rhythmId',
    getParentRoute: () => VisualizationRouteRoute,
  } as any)
const VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute =
  VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRouteImport.update(
    {
      id: '/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer',
      path: '/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer',
      getParentRoute: () => VisualizationRouteRoute,
    } as any,
  )
const EducationTheoryRhythmEducationRoute =
  EducationTheoryRhythmEducationRouteImport.update({
    id: '/theory/rhythm-education',
    path: '/theory/rhythm-education',
    getParentRoute: () => EducationRouteRoute,
  } as any)
const EducationTheoryIntroductionRoute =
  EducationTheoryIntroductionRouteImport.update({
    id: '/theory/Introduction',
    path: '/theory/Introduction',
    getParentRoute: () => EducationRouteRoute,
  } as any)
const EducationGenresRockRoute = EducationGenresRockRouteImport.update({
  id: '/genres/Rock',
  path: '/genres/Rock',
  getParentRoute: () => EducationRouteRoute,
} as any)
const EducationGenresPunkRoute = EducationGenresPunkRouteImport.update({
  id: '/genres/Punk',
  path: '/genres/Punk',
  getParentRoute: () => EducationRouteRoute,
} as any)
const EducationGenresProgRoute = EducationGenresProgRouteImport.update({
  id: '/genres/Prog',
  path: '/genres/Prog',
  getParentRoute: () => EducationRouteRoute,
} as any)
const EducationGenresPopRoute = EducationGenresPopRouteImport.update({
  id: '/genres/Pop',
  path: '/genres/Pop',
  getParentRoute: () => EducationRouteRoute,
} as any)
const EducationGenresMetalRoute = EducationGenresMetalRouteImport.update({
  id: '/genres/Metal',
  path: '/genres/Metal',
  getParentRoute: () => EducationRouteRoute,
} as any)
const EducationGenresJazzRoute = EducationGenresJazzRouteImport.update({
  id: '/genres/Jazz',
  path: '/genres/Jazz',
  getParentRoute: () => EducationRouteRoute,
} as any)
const EducationGenresHipHopRoute = EducationGenresHipHopRouteImport.update({
  id: '/genres/HipHop',
  path: '/genres/HipHop',
  getParentRoute: () => EducationRouteRoute,
} as any)
const EducationGenresGlossaryRoute = EducationGenresGlossaryRouteImport.update({
  id: '/genres/Glossary',
  path: '/genres/Glossary',
  getParentRoute: () => EducationRouteRoute,
} as any)
const EducationGenresEDMRoute = EducationGenresEDMRouteImport.update({
  id: '/genres/EDM',
  path: '/genres/EDM',
  getParentRoute: () => EducationRouteRoute,
} as any)
const EducationGenresAfroCubanRoute =
  EducationGenresAfroCubanRouteImport.update({
    id: '/genres/AfroCuban',
    path: '/genres/AfroCuban',
    getParentRoute: () => EducationRouteRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/education': typeof EducationRouteRouteWithChildren
  '/games': typeof GamesRouteRouteWithChildren
  '/visualization': typeof VisualizationRouteRouteWithChildren
  '/games/And I Will Always Love You': typeof GamesAndIWillAlwaysLoveYouRoute
  '/games/drum-machine': typeof GamesDrumMachineRoute
  '/visualization/metronome': typeof VisualizationMetronomeRoute
  '/visualization/osmd-parser': typeof VisualizationOsmdParserRoute
  '/education/': typeof EducationIndexRoute
  '/games/': typeof GamesIndexRoute
  '/visualization/': typeof VisualizationIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/education/genres/AfroCuban': typeof EducationGenresAfroCubanRoute
  '/education/genres/EDM': typeof EducationGenresEDMRoute
  '/education/genres/Glossary': typeof EducationGenresGlossaryRoute
  '/education/genres/HipHop': typeof EducationGenresHipHopRoute
  '/education/genres/Jazz': typeof EducationGenresJazzRoute
  '/education/genres/Metal': typeof EducationGenresMetalRoute
  '/education/genres/Pop': typeof EducationGenresPopRoute
  '/education/genres/Prog': typeof EducationGenresProgRoute
  '/education/genres/Punk': typeof EducationGenresPunkRoute
  '/education/genres/Rock': typeof EducationGenresRockRoute
  '/education/theory/Introduction': typeof EducationTheoryIntroductionRoute
  '/education/theory/rhythm-education': typeof EducationTheoryRhythmEducationRoute
  '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer': typeof VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute
  '/visualization/rhythms/$rhythmId': typeof VisualizationRhythmsRhythmIdRoute
  '/visualization/rhythms/RhythmIndex': typeof VisualizationRhythmsRhythmIndexRoute
  '/visualization/rhythms/rhythm-visual': typeof VisualizationRhythmsRhythmVisualRoute
  '/education/genres/': typeof EducationGenresIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/And I Will Always Love You': typeof GamesAndIWillAlwaysLoveYouRoute
  '/games/drum-machine': typeof GamesDrumMachineRoute
  '/visualization/metronome': typeof VisualizationMetronomeRoute
  '/visualization/osmd-parser': typeof VisualizationOsmdParserRoute
  '/education': typeof EducationIndexRoute
  '/games': typeof GamesIndexRoute
  '/visualization': typeof VisualizationIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/education/genres/AfroCuban': typeof EducationGenresAfroCubanRoute
  '/education/genres/EDM': typeof EducationGenresEDMRoute
  '/education/genres/Glossary': typeof EducationGenresGlossaryRoute
  '/education/genres/HipHop': typeof EducationGenresHipHopRoute
  '/education/genres/Jazz': typeof EducationGenresJazzRoute
  '/education/genres/Metal': typeof EducationGenresMetalRoute
  '/education/genres/Pop': typeof EducationGenresPopRoute
  '/education/genres/Prog': typeof EducationGenresProgRoute
  '/education/genres/Punk': typeof EducationGenresPunkRoute
  '/education/genres/Rock': typeof EducationGenresRockRoute
  '/education/theory/Introduction': typeof EducationTheoryIntroductionRoute
  '/education/theory/rhythm-education': typeof EducationTheoryRhythmEducationRoute
  '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer': typeof VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute
  '/visualization/rhythms/$rhythmId': typeof VisualizationRhythmsRhythmIdRoute
  '/visualization/rhythms/RhythmIndex': typeof VisualizationRhythmsRhythmIndexRoute
  '/visualization/rhythms/rhythm-visual': typeof VisualizationRhythmsRhythmVisualRoute
  '/education/genres': typeof EducationGenresIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/education': typeof EducationRouteRouteWithChildren
  '/games': typeof GamesRouteRouteWithChildren
  '/visualization': typeof VisualizationRouteRouteWithChildren
  '/games/And I Will Always Love You': typeof GamesAndIWillAlwaysLoveYouRoute
  '/games/drum-machine': typeof GamesDrumMachineRoute
  '/visualization/metronome': typeof VisualizationMetronomeRoute
  '/visualization/osmd-parser': typeof VisualizationOsmdParserRoute
  '/education/': typeof EducationIndexRoute
  '/games/': typeof GamesIndexRoute
  '/visualization/': typeof VisualizationIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/education/genres/AfroCuban': typeof EducationGenresAfroCubanRoute
  '/education/genres/EDM': typeof EducationGenresEDMRoute
  '/education/genres/Glossary': typeof EducationGenresGlossaryRoute
  '/education/genres/HipHop': typeof EducationGenresHipHopRoute
  '/education/genres/Jazz': typeof EducationGenresJazzRoute
  '/education/genres/Metal': typeof EducationGenresMetalRoute
  '/education/genres/Pop': typeof EducationGenresPopRoute
  '/education/genres/Prog': typeof EducationGenresProgRoute
  '/education/genres/Punk': typeof EducationGenresPunkRoute
  '/education/genres/Rock': typeof EducationGenresRockRoute
  '/education/theory/Introduction': typeof EducationTheoryIntroductionRoute
  '/education/theory/rhythm-education': typeof EducationTheoryRhythmEducationRoute
  '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer': typeof VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute
  '/visualization/rhythms/$rhythmId': typeof VisualizationRhythmsRhythmIdRoute
  '/visualization/rhythms/RhythmIndex': typeof VisualizationRhythmsRhythmIndexRoute
  '/visualization/rhythms/rhythm-visual': typeof VisualizationRhythmsRhythmVisualRoute
  '/education/genres/': typeof EducationGenresIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/education'
    | '/games'
    | '/visualization'
    | '/games/And I Will Always Love You'
    | '/games/drum-machine'
    | '/visualization/metronome'
    | '/visualization/osmd-parser'
    | '/education/'
    | '/games/'
    | '/visualization/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/education/genres/AfroCuban'
    | '/education/genres/EDM'
    | '/education/genres/Glossary'
    | '/education/genres/HipHop'
    | '/education/genres/Jazz'
    | '/education/genres/Metal'
    | '/education/genres/Pop'
    | '/education/genres/Prog'
    | '/education/genres/Punk'
    | '/education/genres/Rock'
    | '/education/theory/Introduction'
    | '/education/theory/rhythm-education'
    | '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
    | '/visualization/rhythms/$rhythmId'
    | '/visualization/rhythms/RhythmIndex'
    | '/visualization/rhythms/rhythm-visual'
    | '/education/genres/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/And I Will Always Love You'
    | '/games/drum-machine'
    | '/visualization/metronome'
    | '/visualization/osmd-parser'
    | '/education'
    | '/games'
    | '/visualization'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/education/genres/AfroCuban'
    | '/education/genres/EDM'
    | '/education/genres/Glossary'
    | '/education/genres/HipHop'
    | '/education/genres/Jazz'
    | '/education/genres/Metal'
    | '/education/genres/Pop'
    | '/education/genres/Prog'
    | '/education/genres/Punk'
    | '/education/genres/Rock'
    | '/education/theory/Introduction'
    | '/education/theory/rhythm-education'
    | '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
    | '/visualization/rhythms/$rhythmId'
    | '/visualization/rhythms/RhythmIndex'
    | '/visualization/rhythms/rhythm-visual'
    | '/education/genres'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/education'
    | '/games'
    | '/visualization'
    | '/games/And I Will Always Love You'
    | '/games/drum-machine'
    | '/visualization/metronome'
    | '/visualization/osmd-parser'
    | '/education/'
    | '/games/'
    | '/visualization/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/education/genres/AfroCuban'
    | '/education/genres/EDM'
    | '/education/genres/Glossary'
    | '/education/genres/HipHop'
    | '/education/genres/Jazz'
    | '/education/genres/Metal'
    | '/education/genres/Pop'
    | '/education/genres/Prog'
    | '/education/genres/Punk'
    | '/education/genres/Rock'
    | '/education/theory/Introduction'
    | '/education/theory/rhythm-education'
    | '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
    | '/visualization/rhythms/$rhythmId'
    | '/visualization/rhythms/RhythmIndex'
    | '/visualization/rhythms/rhythm-visual'
    | '/education/genres/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EducationRouteRoute: typeof EducationRouteRouteWithChildren
  GamesRouteRoute: typeof GamesRouteRouteWithChildren
  VisualizationRouteRoute: typeof VisualizationRouteRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualization': {
      id: '/visualization'
      path: '/visualization'
      fullPath: '/visualization'
      preLoaderRoute: typeof VisualizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualization/': {
      id: '/visualization/'
      path: '/'
      fullPath: '/visualization/'
      preLoaderRoute: typeof VisualizationIndexRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRouteRoute
    }
    '/education/': {
      id: '/education/'
      path: '/'
      fullPath: '/education/'
      preLoaderRoute: typeof EducationIndexRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/visualization/osmd-parser': {
      id: '/visualization/osmd-parser'
      path: '/osmd-parser'
      fullPath: '/visualization/osmd-parser'
      preLoaderRoute: typeof VisualizationOsmdParserRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/visualization/metronome': {
      id: '/visualization/metronome'
      path: '/metronome'
      fullPath: '/visualization/metronome'
      preLoaderRoute: typeof VisualizationMetronomeRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/games/drum-machine': {
      id: '/games/drum-machine'
      path: '/drum-machine'
      fullPath: '/games/drum-machine'
      preLoaderRoute: typeof GamesDrumMachineRouteImport
      parentRoute: typeof GamesRouteRoute
    }
    '/games/And I Will Always Love You': {
      id: '/games/And I Will Always Love You'
      path: '/And I Will Always Love You'
      fullPath: '/games/And I Will Always Love You'
      preLoaderRoute: typeof GamesAndIWillAlwaysLoveYouRouteImport
      parentRoute: typeof GamesRouteRoute
    }
    '/education/genres/': {
      id: '/education/genres/'
      path: '/genres'
      fullPath: '/education/genres/'
      preLoaderRoute: typeof EducationGenresIndexRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/visualization/rhythms/rhythm-visual': {
      id: '/visualization/rhythms/rhythm-visual'
      path: '/rhythms/rhythm-visual'
      fullPath: '/visualization/rhythms/rhythm-visual'
      preLoaderRoute: typeof VisualizationRhythmsRhythmVisualRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/visualization/rhythms/RhythmIndex': {
      id: '/visualization/rhythms/RhythmIndex'
      path: '/rhythms/RhythmIndex'
      fullPath: '/visualization/rhythms/RhythmIndex'
      preLoaderRoute: typeof VisualizationRhythmsRhythmIndexRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/visualization/rhythms/$rhythmId': {
      id: '/visualization/rhythms/$rhythmId'
      path: '/rhythms/$rhythmId'
      fullPath: '/visualization/rhythms/$rhythmId'
      preLoaderRoute: typeof VisualizationRhythmsRhythmIdRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer': {
      id: '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
      path: '/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
      fullPath: '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
      preLoaderRoute: typeof VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/education/theory/rhythm-education': {
      id: '/education/theory/rhythm-education'
      path: '/theory/rhythm-education'
      fullPath: '/education/theory/rhythm-education'
      preLoaderRoute: typeof EducationTheoryRhythmEducationRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/theory/Introduction': {
      id: '/education/theory/Introduction'
      path: '/theory/Introduction'
      fullPath: '/education/theory/Introduction'
      preLoaderRoute: typeof EducationTheoryIntroductionRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/Rock': {
      id: '/education/genres/Rock'
      path: '/genres/Rock'
      fullPath: '/education/genres/Rock'
      preLoaderRoute: typeof EducationGenresRockRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/Punk': {
      id: '/education/genres/Punk'
      path: '/genres/Punk'
      fullPath: '/education/genres/Punk'
      preLoaderRoute: typeof EducationGenresPunkRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/Prog': {
      id: '/education/genres/Prog'
      path: '/genres/Prog'
      fullPath: '/education/genres/Prog'
      preLoaderRoute: typeof EducationGenresProgRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/Pop': {
      id: '/education/genres/Pop'
      path: '/genres/Pop'
      fullPath: '/education/genres/Pop'
      preLoaderRoute: typeof EducationGenresPopRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/Metal': {
      id: '/education/genres/Metal'
      path: '/genres/Metal'
      fullPath: '/education/genres/Metal'
      preLoaderRoute: typeof EducationGenresMetalRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/Jazz': {
      id: '/education/genres/Jazz'
      path: '/genres/Jazz'
      fullPath: '/education/genres/Jazz'
      preLoaderRoute: typeof EducationGenresJazzRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/HipHop': {
      id: '/education/genres/HipHop'
      path: '/genres/HipHop'
      fullPath: '/education/genres/HipHop'
      preLoaderRoute: typeof EducationGenresHipHopRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/Glossary': {
      id: '/education/genres/Glossary'
      path: '/genres/Glossary'
      fullPath: '/education/genres/Glossary'
      preLoaderRoute: typeof EducationGenresGlossaryRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/EDM': {
      id: '/education/genres/EDM'
      path: '/genres/EDM'
      fullPath: '/education/genres/EDM'
      preLoaderRoute: typeof EducationGenresEDMRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/AfroCuban': {
      id: '/education/genres/AfroCuban'
      path: '/genres/AfroCuban'
      fullPath: '/education/genres/AfroCuban'
      preLoaderRoute: typeof EducationGenresAfroCubanRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EducationRouteRouteChildren {
  EducationIndexRoute: typeof EducationIndexRoute
  EducationGenresAfroCubanRoute: typeof EducationGenresAfroCubanRoute
  EducationGenresEDMRoute: typeof EducationGenresEDMRoute
  EducationGenresGlossaryRoute: typeof EducationGenresGlossaryRoute
  EducationGenresHipHopRoute: typeof EducationGenresHipHopRoute
  EducationGenresJazzRoute: typeof EducationGenresJazzRoute
  EducationGenresMetalRoute: typeof EducationGenresMetalRoute
  EducationGenresPopRoute: typeof EducationGenresPopRoute
  EducationGenresProgRoute: typeof EducationGenresProgRoute
  EducationGenresPunkRoute: typeof EducationGenresPunkRoute
  EducationGenresRockRoute: typeof EducationGenresRockRoute
  EducationTheoryIntroductionRoute: typeof EducationTheoryIntroductionRoute
  EducationTheoryRhythmEducationRoute: typeof EducationTheoryRhythmEducationRoute
  EducationGenresIndexRoute: typeof EducationGenresIndexRoute
}

const EducationRouteRouteChildren: EducationRouteRouteChildren = {
  EducationIndexRoute: EducationIndexRoute,
  EducationGenresAfroCubanRoute: EducationGenresAfroCubanRoute,
  EducationGenresEDMRoute: EducationGenresEDMRoute,
  EducationGenresGlossaryRoute: EducationGenresGlossaryRoute,
  EducationGenresHipHopRoute: EducationGenresHipHopRoute,
  EducationGenresJazzRoute: EducationGenresJazzRoute,
  EducationGenresMetalRoute: EducationGenresMetalRoute,
  EducationGenresPopRoute: EducationGenresPopRoute,
  EducationGenresProgRoute: EducationGenresProgRoute,
  EducationGenresPunkRoute: EducationGenresPunkRoute,
  EducationGenresRockRoute: EducationGenresRockRoute,
  EducationTheoryIntroductionRoute: EducationTheoryIntroductionRoute,
  EducationTheoryRhythmEducationRoute: EducationTheoryRhythmEducationRoute,
  EducationGenresIndexRoute: EducationGenresIndexRoute,
}

const EducationRouteRouteWithChildren = EducationRouteRoute._addFileChildren(
  EducationRouteRouteChildren,
)

interface GamesRouteRouteChildren {
  GamesAndIWillAlwaysLoveYouRoute: typeof GamesAndIWillAlwaysLoveYouRoute
  GamesDrumMachineRoute: typeof GamesDrumMachineRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteRouteChildren: GamesRouteRouteChildren = {
  GamesAndIWillAlwaysLoveYouRoute: GamesAndIWillAlwaysLoveYouRoute,
  GamesDrumMachineRoute: GamesDrumMachineRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteRouteWithChildren = GamesRouteRoute._addFileChildren(
  GamesRouteRouteChildren,
)

interface VisualizationRouteRouteChildren {
  VisualizationMetronomeRoute: typeof VisualizationMetronomeRoute
  VisualizationOsmdParserRoute: typeof VisualizationOsmdParserRoute
  VisualizationIndexRoute: typeof VisualizationIndexRoute
  VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute: typeof VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute
  VisualizationRhythmsRhythmIdRoute: typeof VisualizationRhythmsRhythmIdRoute
  VisualizationRhythmsRhythmIndexRoute: typeof VisualizationRhythmsRhythmIndexRoute
  VisualizationRhythmsRhythmVisualRoute: typeof VisualizationRhythmsRhythmVisualRoute
}

const VisualizationRouteRouteChildren: VisualizationRouteRouteChildren = {
  VisualizationMetronomeRoute: VisualizationMetronomeRoute,
  VisualizationOsmdParserRoute: VisualizationOsmdParserRoute,
  VisualizationIndexRoute: VisualizationIndexRoute,
  VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute:
    VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute,
  VisualizationRhythmsRhythmIdRoute: VisualizationRhythmsRhythmIdRoute,
  VisualizationRhythmsRhythmIndexRoute: VisualizationRhythmsRhythmIndexRoute,
  VisualizationRhythmsRhythmVisualRoute: VisualizationRhythmsRhythmVisualRoute,
}

const VisualizationRouteRouteWithChildren =
  VisualizationRouteRoute._addFileChildren(VisualizationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EducationRouteRoute: EducationRouteRouteWithChildren,
  GamesRouteRoute: GamesRouteRouteWithChildren,
  VisualizationRouteRoute: VisualizationRouteRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
