/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizationRouteRouteImport } from './routes/visualization/route'
import { Route as GamesRouteRouteImport } from './routes/games/route'
import { Route as EducationRouteRouteImport } from './routes/education/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualizationIndexRouteImport } from './routes/visualization/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as EducationIndexRouteImport } from './routes/education/index'
import { Route as VisualizationOsmdParserRouteImport } from './routes/visualization/osmd-parser'
import { Route as VisualizationMetronomeRouteImport } from './routes/visualization/metronome'
import { Route as GamesWhitneyHoustonChallengeRouteImport } from './routes/games/whitney-houston-challenge'
import { Route as GamesDrumMachineRouteImport } from './routes/games/drum-machine'
import { Route as EducationGenresRouteRouteImport } from './routes/education/genres/route'
import { Route as EducationGenresIndexRouteImport } from './routes/education/genres/index'
import { Route as VisualizationRhythmsRhythmVisualRouteImport } from './routes/visualization/rhythms/rhythm-visual'
import { Route as VisualizationRhythmsRhythmIndexRouteImport } from './routes/visualization/rhythms/RhythmIndex'
import { Route as VisualizationRhythmsRhythmIdRouteImport } from './routes/visualization/rhythms/$rhythmId'
import { Route as VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRouteImport } from './routes/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
import { Route as EducationTheoryRhythmEducationRouteImport } from './routes/education/theory/rhythm-education'
import { Route as EducationTheoryIntroductionRouteImport } from './routes/education/theory/Introduction'
import { Route as EducationGenresGlossaryRouteImport } from './routes/education/genres/Glossary'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as EducationGenresPunkRockIndexRouteImport } from './routes/education/genres/punk-rock/index'
import { Route as EducationGenresProgIndexRouteImport } from './routes/education/genres/prog/index'
import { Route as EducationGenresPopIndexRouteImport } from './routes/education/genres/pop/index'
import { Route as EducationGenresMetalIndexRouteImport } from './routes/education/genres/metal/index'
import { Route as EducationGenresJazzIndexRouteImport } from './routes/education/genres/jazz/index'
import { Route as EducationGenresHipHopIndexRouteImport } from './routes/education/genres/hip-hop/index'
import { Route as EducationGenresEdmIndexRouteImport } from './routes/education/genres/edm/index'
import { Route as EducationGenresClassicRockIndexRouteImport } from './routes/education/genres/classic-rock/index'
import { Route as EducationGenresAfroCubanIndexRouteImport } from './routes/education/genres/afro-cuban/index'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const VisualizationRouteRoute = VisualizationRouteRouteImport.update({
  id: '/visualization',
  path: '/visualization',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRouteRoute = GamesRouteRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRouteRoute = EducationRouteRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationIndexRoute = VisualizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisualizationRouteRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRouteRoute,
} as any)
const EducationIndexRoute = EducationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducationRouteRoute,
} as any)
const VisualizationOsmdParserRoute = VisualizationOsmdParserRouteImport.update({
  id: '/osmd-parser',
  path: '/osmd-parser',
  getParentRoute: () => VisualizationRouteRoute,
} as any)
const VisualizationMetronomeRoute = VisualizationMetronomeRouteImport.update({
  id: '/metronome',
  path: '/metronome',
  getParentRoute: () => VisualizationRouteRoute,
} as any)
const GamesWhitneyHoustonChallengeRoute =
  GamesWhitneyHoustonChallengeRouteImport.update({
    id: '/whitney-houston-challenge',
    path: '/whitney-houston-challenge',
    getParentRoute: () => GamesRouteRoute,
  } as any)
const GamesDrumMachineRoute = GamesDrumMachineRouteImport.update({
  id: '/drum-machine',
  path: '/drum-machine',
  getParentRoute: () => GamesRouteRoute,
} as any)
const EducationGenresRouteRoute = EducationGenresRouteRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => EducationRouteRoute,
} as any)
const EducationGenresIndexRoute = EducationGenresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EducationGenresRouteRoute,
} as any)
const VisualizationRhythmsRhythmVisualRoute =
  VisualizationRhythmsRhythmVisualRouteImport.update({
    id: '/rhythms/rhythm-visual',
    path: '/rhythms/rhythm-visual',
    getParentRoute: () => VisualizationRouteRoute,
  } as any)
const VisualizationRhythmsRhythmIndexRoute =
  VisualizationRhythmsRhythmIndexRouteImport.update({
    id: '/rhythms/RhythmIndex',
    path: '/rhythms/RhythmIndex',
    getParentRoute: () => VisualizationRouteRoute,
  } as any)
const VisualizationRhythmsRhythmIdRoute =
  VisualizationRhythmsRhythmIdRouteImport.update({
    id: '/rhythms/$rhythmId',
    path: '/rhythms/$rhythmId',
    getParentRoute: () => VisualizationRouteRoute,
  } as any)
const VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute =
  VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRouteImport.update(
    {
      id: '/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer',
      path: '/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer',
      getParentRoute: () => VisualizationRouteRoute,
    } as any,
  )
const EducationTheoryRhythmEducationRoute =
  EducationTheoryRhythmEducationRouteImport.update({
    id: '/theory/rhythm-education',
    path: '/theory/rhythm-education',
    getParentRoute: () => EducationRouteRoute,
  } as any)
const EducationTheoryIntroductionRoute =
  EducationTheoryIntroductionRouteImport.update({
    id: '/theory/Introduction',
    path: '/theory/Introduction',
    getParentRoute: () => EducationRouteRoute,
  } as any)
const EducationGenresGlossaryRoute = EducationGenresGlossaryRouteImport.update({
  id: '/Glossary',
  path: '/Glossary',
  getParentRoute: () => EducationGenresRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationGenresPunkRockIndexRoute =
  EducationGenresPunkRockIndexRouteImport.update({
    id: '/punk-rock/',
    path: '/punk-rock/',
    getParentRoute: () => EducationGenresRouteRoute,
  } as any)
const EducationGenresProgIndexRoute =
  EducationGenresProgIndexRouteImport.update({
    id: '/prog/',
    path: '/prog/',
    getParentRoute: () => EducationGenresRouteRoute,
  } as any)
const EducationGenresPopIndexRoute = EducationGenresPopIndexRouteImport.update({
  id: '/pop/',
  path: '/pop/',
  getParentRoute: () => EducationGenresRouteRoute,
} as any)
const EducationGenresMetalIndexRoute =
  EducationGenresMetalIndexRouteImport.update({
    id: '/metal/',
    path: '/metal/',
    getParentRoute: () => EducationGenresRouteRoute,
  } as any)
const EducationGenresJazzIndexRoute =
  EducationGenresJazzIndexRouteImport.update({
    id: '/jazz/',
    path: '/jazz/',
    getParentRoute: () => EducationGenresRouteRoute,
  } as any)
const EducationGenresHipHopIndexRoute =
  EducationGenresHipHopIndexRouteImport.update({
    id: '/hip-hop/',
    path: '/hip-hop/',
    getParentRoute: () => EducationGenresRouteRoute,
  } as any)
const EducationGenresEdmIndexRoute = EducationGenresEdmIndexRouteImport.update({
  id: '/edm/',
  path: '/edm/',
  getParentRoute: () => EducationGenresRouteRoute,
} as any)
const EducationGenresClassicRockIndexRoute =
  EducationGenresClassicRockIndexRouteImport.update({
    id: '/classic-rock/',
    path: '/classic-rock/',
    getParentRoute: () => EducationGenresRouteRoute,
  } as any)
const EducationGenresAfroCubanIndexRoute =
  EducationGenresAfroCubanIndexRouteImport.update({
    id: '/afro-cuban/',
    path: '/afro-cuban/',
    getParentRoute: () => EducationGenresRouteRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/education': typeof EducationRouteRouteWithChildren
  '/games': typeof GamesRouteRouteWithChildren
  '/visualization': typeof VisualizationRouteRouteWithChildren
  '/education/genres': typeof EducationGenresRouteRouteWithChildren
  '/games/drum-machine': typeof GamesDrumMachineRoute
  '/games/whitney-houston-challenge': typeof GamesWhitneyHoustonChallengeRoute
  '/visualization/metronome': typeof VisualizationMetronomeRoute
  '/visualization/osmd-parser': typeof VisualizationOsmdParserRoute
  '/education/': typeof EducationIndexRoute
  '/games/': typeof GamesIndexRoute
  '/visualization/': typeof VisualizationIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/education/genres/Glossary': typeof EducationGenresGlossaryRoute
  '/education/theory/Introduction': typeof EducationTheoryIntroductionRoute
  '/education/theory/rhythm-education': typeof EducationTheoryRhythmEducationRoute
  '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer': typeof VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute
  '/visualization/rhythms/$rhythmId': typeof VisualizationRhythmsRhythmIdRoute
  '/visualization/rhythms/RhythmIndex': typeof VisualizationRhythmsRhythmIndexRoute
  '/visualization/rhythms/rhythm-visual': typeof VisualizationRhythmsRhythmVisualRoute
  '/education/genres/': typeof EducationGenresIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/education/genres/afro-cuban/': typeof EducationGenresAfroCubanIndexRoute
  '/education/genres/classic-rock/': typeof EducationGenresClassicRockIndexRoute
  '/education/genres/edm/': typeof EducationGenresEdmIndexRoute
  '/education/genres/hip-hop/': typeof EducationGenresHipHopIndexRoute
  '/education/genres/jazz/': typeof EducationGenresJazzIndexRoute
  '/education/genres/metal/': typeof EducationGenresMetalIndexRoute
  '/education/genres/pop/': typeof EducationGenresPopIndexRoute
  '/education/genres/prog/': typeof EducationGenresProgIndexRoute
  '/education/genres/punk-rock/': typeof EducationGenresPunkRockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/drum-machine': typeof GamesDrumMachineRoute
  '/games/whitney-houston-challenge': typeof GamesWhitneyHoustonChallengeRoute
  '/visualization/metronome': typeof VisualizationMetronomeRoute
  '/visualization/osmd-parser': typeof VisualizationOsmdParserRoute
  '/education': typeof EducationIndexRoute
  '/games': typeof GamesIndexRoute
  '/visualization': typeof VisualizationIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/education/genres/Glossary': typeof EducationGenresGlossaryRoute
  '/education/theory/Introduction': typeof EducationTheoryIntroductionRoute
  '/education/theory/rhythm-education': typeof EducationTheoryRhythmEducationRoute
  '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer': typeof VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute
  '/visualization/rhythms/$rhythmId': typeof VisualizationRhythmsRhythmIdRoute
  '/visualization/rhythms/RhythmIndex': typeof VisualizationRhythmsRhythmIndexRoute
  '/visualization/rhythms/rhythm-visual': typeof VisualizationRhythmsRhythmVisualRoute
  '/education/genres': typeof EducationGenresIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/education/genres/afro-cuban': typeof EducationGenresAfroCubanIndexRoute
  '/education/genres/classic-rock': typeof EducationGenresClassicRockIndexRoute
  '/education/genres/edm': typeof EducationGenresEdmIndexRoute
  '/education/genres/hip-hop': typeof EducationGenresHipHopIndexRoute
  '/education/genres/jazz': typeof EducationGenresJazzIndexRoute
  '/education/genres/metal': typeof EducationGenresMetalIndexRoute
  '/education/genres/pop': typeof EducationGenresPopIndexRoute
  '/education/genres/prog': typeof EducationGenresProgIndexRoute
  '/education/genres/punk-rock': typeof EducationGenresPunkRockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/education': typeof EducationRouteRouteWithChildren
  '/games': typeof GamesRouteRouteWithChildren
  '/visualization': typeof VisualizationRouteRouteWithChildren
  '/education/genres': typeof EducationGenresRouteRouteWithChildren
  '/games/drum-machine': typeof GamesDrumMachineRoute
  '/games/whitney-houston-challenge': typeof GamesWhitneyHoustonChallengeRoute
  '/visualization/metronome': typeof VisualizationMetronomeRoute
  '/visualization/osmd-parser': typeof VisualizationOsmdParserRoute
  '/education/': typeof EducationIndexRoute
  '/games/': typeof GamesIndexRoute
  '/visualization/': typeof VisualizationIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/education/genres/Glossary': typeof EducationGenresGlossaryRoute
  '/education/theory/Introduction': typeof EducationTheoryIntroductionRoute
  '/education/theory/rhythm-education': typeof EducationTheoryRhythmEducationRoute
  '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer': typeof VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute
  '/visualization/rhythms/$rhythmId': typeof VisualizationRhythmsRhythmIdRoute
  '/visualization/rhythms/RhythmIndex': typeof VisualizationRhythmsRhythmIndexRoute
  '/visualization/rhythms/rhythm-visual': typeof VisualizationRhythmsRhythmVisualRoute
  '/education/genres/': typeof EducationGenresIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/education/genres/afro-cuban/': typeof EducationGenresAfroCubanIndexRoute
  '/education/genres/classic-rock/': typeof EducationGenresClassicRockIndexRoute
  '/education/genres/edm/': typeof EducationGenresEdmIndexRoute
  '/education/genres/hip-hop/': typeof EducationGenresHipHopIndexRoute
  '/education/genres/jazz/': typeof EducationGenresJazzIndexRoute
  '/education/genres/metal/': typeof EducationGenresMetalIndexRoute
  '/education/genres/pop/': typeof EducationGenresPopIndexRoute
  '/education/genres/prog/': typeof EducationGenresProgIndexRoute
  '/education/genres/punk-rock/': typeof EducationGenresPunkRockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/education'
    | '/games'
    | '/visualization'
    | '/education/genres'
    | '/games/drum-machine'
    | '/games/whitney-houston-challenge'
    | '/visualization/metronome'
    | '/visualization/osmd-parser'
    | '/education/'
    | '/games/'
    | '/visualization/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/education/genres/Glossary'
    | '/education/theory/Introduction'
    | '/education/theory/rhythm-education'
    | '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
    | '/visualization/rhythms/$rhythmId'
    | '/visualization/rhythms/RhythmIndex'
    | '/visualization/rhythms/rhythm-visual'
    | '/education/genres/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/education/genres/afro-cuban/'
    | '/education/genres/classic-rock/'
    | '/education/genres/edm/'
    | '/education/genres/hip-hop/'
    | '/education/genres/jazz/'
    | '/education/genres/metal/'
    | '/education/genres/pop/'
    | '/education/genres/prog/'
    | '/education/genres/punk-rock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/drum-machine'
    | '/games/whitney-houston-challenge'
    | '/visualization/metronome'
    | '/visualization/osmd-parser'
    | '/education'
    | '/games'
    | '/visualization'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/education/genres/Glossary'
    | '/education/theory/Introduction'
    | '/education/theory/rhythm-education'
    | '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
    | '/visualization/rhythms/$rhythmId'
    | '/visualization/rhythms/RhythmIndex'
    | '/visualization/rhythms/rhythm-visual'
    | '/education/genres'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/education/genres/afro-cuban'
    | '/education/genres/classic-rock'
    | '/education/genres/edm'
    | '/education/genres/hip-hop'
    | '/education/genres/jazz'
    | '/education/genres/metal'
    | '/education/genres/pop'
    | '/education/genres/prog'
    | '/education/genres/punk-rock'
  id:
    | '__root__'
    | '/'
    | '/education'
    | '/games'
    | '/visualization'
    | '/education/genres'
    | '/games/drum-machine'
    | '/games/whitney-houston-challenge'
    | '/visualization/metronome'
    | '/visualization/osmd-parser'
    | '/education/'
    | '/games/'
    | '/visualization/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/education/genres/Glossary'
    | '/education/theory/Introduction'
    | '/education/theory/rhythm-education'
    | '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
    | '/visualization/rhythms/$rhythmId'
    | '/visualization/rhythms/RhythmIndex'
    | '/visualization/rhythms/rhythm-visual'
    | '/education/genres/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/education/genres/afro-cuban/'
    | '/education/genres/classic-rock/'
    | '/education/genres/edm/'
    | '/education/genres/hip-hop/'
    | '/education/genres/jazz/'
    | '/education/genres/metal/'
    | '/education/genres/pop/'
    | '/education/genres/prog/'
    | '/education/genres/punk-rock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EducationRouteRoute: typeof EducationRouteRouteWithChildren
  GamesRouteRoute: typeof GamesRouteRouteWithChildren
  VisualizationRouteRoute: typeof VisualizationRouteRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualization': {
      id: '/visualization'
      path: '/visualization'
      fullPath: '/visualization'
      preLoaderRoute: typeof VisualizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualization/': {
      id: '/visualization/'
      path: '/'
      fullPath: '/visualization/'
      preLoaderRoute: typeof VisualizationIndexRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRouteRoute
    }
    '/education/': {
      id: '/education/'
      path: '/'
      fullPath: '/education/'
      preLoaderRoute: typeof EducationIndexRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/visualization/osmd-parser': {
      id: '/visualization/osmd-parser'
      path: '/osmd-parser'
      fullPath: '/visualization/osmd-parser'
      preLoaderRoute: typeof VisualizationOsmdParserRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/visualization/metronome': {
      id: '/visualization/metronome'
      path: '/metronome'
      fullPath: '/visualization/metronome'
      preLoaderRoute: typeof VisualizationMetronomeRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/games/whitney-houston-challenge': {
      id: '/games/whitney-houston-challenge'
      path: '/whitney-houston-challenge'
      fullPath: '/games/whitney-houston-challenge'
      preLoaderRoute: typeof GamesWhitneyHoustonChallengeRouteImport
      parentRoute: typeof GamesRouteRoute
    }
    '/games/drum-machine': {
      id: '/games/drum-machine'
      path: '/drum-machine'
      fullPath: '/games/drum-machine'
      preLoaderRoute: typeof GamesDrumMachineRouteImport
      parentRoute: typeof GamesRouteRoute
    }
    '/education/genres': {
      id: '/education/genres'
      path: '/genres'
      fullPath: '/education/genres'
      preLoaderRoute: typeof EducationGenresRouteRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/': {
      id: '/education/genres/'
      path: '/'
      fullPath: '/education/genres/'
      preLoaderRoute: typeof EducationGenresIndexRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/visualization/rhythms/rhythm-visual': {
      id: '/visualization/rhythms/rhythm-visual'
      path: '/rhythms/rhythm-visual'
      fullPath: '/visualization/rhythms/rhythm-visual'
      preLoaderRoute: typeof VisualizationRhythmsRhythmVisualRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/visualization/rhythms/RhythmIndex': {
      id: '/visualization/rhythms/RhythmIndex'
      path: '/rhythms/RhythmIndex'
      fullPath: '/visualization/rhythms/RhythmIndex'
      preLoaderRoute: typeof VisualizationRhythmsRhythmIndexRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/visualization/rhythms/$rhythmId': {
      id: '/visualization/rhythms/$rhythmId'
      path: '/rhythms/$rhythmId'
      fullPath: '/visualization/rhythms/$rhythmId'
      preLoaderRoute: typeof VisualizationRhythmsRhythmIdRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer': {
      id: '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
      path: '/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
      fullPath: '/visualization/DVD-Polyrhythm-Visualizer/DvdPolyrhythmVisualizer'
      preLoaderRoute: typeof VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRouteImport
      parentRoute: typeof VisualizationRouteRoute
    }
    '/education/theory/rhythm-education': {
      id: '/education/theory/rhythm-education'
      path: '/theory/rhythm-education'
      fullPath: '/education/theory/rhythm-education'
      preLoaderRoute: typeof EducationTheoryRhythmEducationRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/theory/Introduction': {
      id: '/education/theory/Introduction'
      path: '/theory/Introduction'
      fullPath: '/education/theory/Introduction'
      preLoaderRoute: typeof EducationTheoryIntroductionRouteImport
      parentRoute: typeof EducationRouteRoute
    }
    '/education/genres/Glossary': {
      id: '/education/genres/Glossary'
      path: '/Glossary'
      fullPath: '/education/genres/Glossary'
      preLoaderRoute: typeof EducationGenresGlossaryRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/genres/punk-rock/': {
      id: '/education/genres/punk-rock/'
      path: '/punk-rock'
      fullPath: '/education/genres/punk-rock/'
      preLoaderRoute: typeof EducationGenresPunkRockIndexRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/education/genres/prog/': {
      id: '/education/genres/prog/'
      path: '/prog'
      fullPath: '/education/genres/prog/'
      preLoaderRoute: typeof EducationGenresProgIndexRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/education/genres/pop/': {
      id: '/education/genres/pop/'
      path: '/pop'
      fullPath: '/education/genres/pop/'
      preLoaderRoute: typeof EducationGenresPopIndexRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/education/genres/metal/': {
      id: '/education/genres/metal/'
      path: '/metal'
      fullPath: '/education/genres/metal/'
      preLoaderRoute: typeof EducationGenresMetalIndexRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/education/genres/jazz/': {
      id: '/education/genres/jazz/'
      path: '/jazz'
      fullPath: '/education/genres/jazz/'
      preLoaderRoute: typeof EducationGenresJazzIndexRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/education/genres/hip-hop/': {
      id: '/education/genres/hip-hop/'
      path: '/hip-hop'
      fullPath: '/education/genres/hip-hop/'
      preLoaderRoute: typeof EducationGenresHipHopIndexRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/education/genres/edm/': {
      id: '/education/genres/edm/'
      path: '/edm'
      fullPath: '/education/genres/edm/'
      preLoaderRoute: typeof EducationGenresEdmIndexRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/education/genres/classic-rock/': {
      id: '/education/genres/classic-rock/'
      path: '/classic-rock'
      fullPath: '/education/genres/classic-rock/'
      preLoaderRoute: typeof EducationGenresClassicRockIndexRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/education/genres/afro-cuban/': {
      id: '/education/genres/afro-cuban/'
      path: '/afro-cuban'
      fullPath: '/education/genres/afro-cuban/'
      preLoaderRoute: typeof EducationGenresAfroCubanIndexRouteImport
      parentRoute: typeof EducationGenresRouteRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EducationGenresRouteRouteChildren {
  EducationGenresGlossaryRoute: typeof EducationGenresGlossaryRoute
  EducationGenresIndexRoute: typeof EducationGenresIndexRoute
  EducationGenresAfroCubanIndexRoute: typeof EducationGenresAfroCubanIndexRoute
  EducationGenresClassicRockIndexRoute: typeof EducationGenresClassicRockIndexRoute
  EducationGenresEdmIndexRoute: typeof EducationGenresEdmIndexRoute
  EducationGenresHipHopIndexRoute: typeof EducationGenresHipHopIndexRoute
  EducationGenresJazzIndexRoute: typeof EducationGenresJazzIndexRoute
  EducationGenresMetalIndexRoute: typeof EducationGenresMetalIndexRoute
  EducationGenresPopIndexRoute: typeof EducationGenresPopIndexRoute
  EducationGenresProgIndexRoute: typeof EducationGenresProgIndexRoute
  EducationGenresPunkRockIndexRoute: typeof EducationGenresPunkRockIndexRoute
}

const EducationGenresRouteRouteChildren: EducationGenresRouteRouteChildren = {
  EducationGenresGlossaryRoute: EducationGenresGlossaryRoute,
  EducationGenresIndexRoute: EducationGenresIndexRoute,
  EducationGenresAfroCubanIndexRoute: EducationGenresAfroCubanIndexRoute,
  EducationGenresClassicRockIndexRoute: EducationGenresClassicRockIndexRoute,
  EducationGenresEdmIndexRoute: EducationGenresEdmIndexRoute,
  EducationGenresHipHopIndexRoute: EducationGenresHipHopIndexRoute,
  EducationGenresJazzIndexRoute: EducationGenresJazzIndexRoute,
  EducationGenresMetalIndexRoute: EducationGenresMetalIndexRoute,
  EducationGenresPopIndexRoute: EducationGenresPopIndexRoute,
  EducationGenresProgIndexRoute: EducationGenresProgIndexRoute,
  EducationGenresPunkRockIndexRoute: EducationGenresPunkRockIndexRoute,
}

const EducationGenresRouteRouteWithChildren =
  EducationGenresRouteRoute._addFileChildren(EducationGenresRouteRouteChildren)

interface EducationRouteRouteChildren {
  EducationGenresRouteRoute: typeof EducationGenresRouteRouteWithChildren
  EducationIndexRoute: typeof EducationIndexRoute
  EducationTheoryIntroductionRoute: typeof EducationTheoryIntroductionRoute
  EducationTheoryRhythmEducationRoute: typeof EducationTheoryRhythmEducationRoute
}

const EducationRouteRouteChildren: EducationRouteRouteChildren = {
  EducationGenresRouteRoute: EducationGenresRouteRouteWithChildren,
  EducationIndexRoute: EducationIndexRoute,
  EducationTheoryIntroductionRoute: EducationTheoryIntroductionRoute,
  EducationTheoryRhythmEducationRoute: EducationTheoryRhythmEducationRoute,
}

const EducationRouteRouteWithChildren = EducationRouteRoute._addFileChildren(
  EducationRouteRouteChildren,
)

interface GamesRouteRouteChildren {
  GamesDrumMachineRoute: typeof GamesDrumMachineRoute
  GamesWhitneyHoustonChallengeRoute: typeof GamesWhitneyHoustonChallengeRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteRouteChildren: GamesRouteRouteChildren = {
  GamesDrumMachineRoute: GamesDrumMachineRoute,
  GamesWhitneyHoustonChallengeRoute: GamesWhitneyHoustonChallengeRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteRouteWithChildren = GamesRouteRoute._addFileChildren(
  GamesRouteRouteChildren,
)

interface VisualizationRouteRouteChildren {
  VisualizationMetronomeRoute: typeof VisualizationMetronomeRoute
  VisualizationOsmdParserRoute: typeof VisualizationOsmdParserRoute
  VisualizationIndexRoute: typeof VisualizationIndexRoute
  VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute: typeof VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute
  VisualizationRhythmsRhythmIdRoute: typeof VisualizationRhythmsRhythmIdRoute
  VisualizationRhythmsRhythmIndexRoute: typeof VisualizationRhythmsRhythmIndexRoute
  VisualizationRhythmsRhythmVisualRoute: typeof VisualizationRhythmsRhythmVisualRoute
}

const VisualizationRouteRouteChildren: VisualizationRouteRouteChildren = {
  VisualizationMetronomeRoute: VisualizationMetronomeRoute,
  VisualizationOsmdParserRoute: VisualizationOsmdParserRoute,
  VisualizationIndexRoute: VisualizationIndexRoute,
  VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute:
    VisualizationDVDPolyrhythmVisualizerDvdPolyrhythmVisualizerRoute,
  VisualizationRhythmsRhythmIdRoute: VisualizationRhythmsRhythmIdRoute,
  VisualizationRhythmsRhythmIndexRoute: VisualizationRhythmsRhythmIndexRoute,
  VisualizationRhythmsRhythmVisualRoute: VisualizationRhythmsRhythmVisualRoute,
}

const VisualizationRouteRouteWithChildren =
  VisualizationRouteRoute._addFileChildren(VisualizationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EducationRouteRoute: EducationRouteRouteWithChildren,
  GamesRouteRoute: GamesRouteRouteWithChildren,
  VisualizationRouteRoute: VisualizationRouteRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
